### PR TITLE
Load priorities when there is no priorityscheme

### PR DESCRIPTION
**Pull request by Daverlo**
FYI @nickfyson

### CODE REVIEW

**Comment by nickfyson** [comment]
LGTM

I'm unsure about the NPE check added in that other PR though. What are we trying to achieve with it? If priority is null it results in a _diffferent_ problem, but it's still a 500 status?

**Comment by Seyfel** [comment]
The problem with the NPE is that if its thrown it sends the full stack trace as the response.

**Comment by Daverlo** [comment]
The problem with the NPE is that if its thrown it sends the full stack trace as the response.

**Comment by nickfyson** [comment]
Yep, Arthur's pull request fixed my concern with it.

**Pull request merged**
